version: '3.8'

services:
  redis-node1:
    image: redis-ubuntu:20.04
    container_name: redis-node1
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "6389:6379"
    networks:
      - redis-cluster

  redis-node2:
    image: redis-ubuntu:20.04
    container_name: redis-node2
    command: ["redis-server", "--port", "6380", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "6390:6380"
    networks:
      - redis-cluster

  redis-node3:
    image: redis-ubuntu:20.04
    container_name: redis-node3
    command: ["redis-server", "--port", "6381", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "6391:6381"
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
