#cloud-config
debug:
  verbose: true
cloud_init_modules:
 - migrator
 - seed_random
 - write-files
 - growpart
 - resizefs
 - set_hostname
 - update_hostname
 - update_etc_hosts
 - users-groups
 - ssh
 - runcmd
users:
  - name: user
    groups: sudo
    lock_passwd: false
    passwd: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    expire: False
chpasswd:
  list:
    - "user:user"
  expire: False

timezone: "Europe/Moscow"
fqdn: "redis"

runcmd:
  - git clone git clone https://github.com/Salvation2090/Reddis.git .
  - cd Reddis
  - sudo chmod u+x install_redis.sh
  - sudo bash install_redis.sh
